# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(THEMOVIEDB_URL): 'https://api.themoviedb.org'
    env(THEMOVIEDB_URL_IMG): 'https://image.tmdb.org/t/p/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MovieServiceInterface: '@App\Service\TheMovieDBService'

    App\Service\TheMovieDBService:
        bind:
            string $theMovieDBUrl: '%env(THEMOVIEDB_URL)%'
            string $theMovieDBApiKey: '%env(THEMOVIEDB_API_KEY)%'
            string $theMovieDBAUrlImg: '%env(THEMOVIEDB_URL_IMG)%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

#    string $theMovieDBUrl: '%env(string:THEMOVIEDB_URL)%'
#    string $theMovieDBApiKey: '%env(string:THEMOVIEDB_API_KEY)%'
